---
driver:
  name: vagrant

provisioner:
  name: salt_solo
  is_file_root: true
  # Use this section (and comment out the `threatstack.sls` definition in the `pillars` section)
  # to grab pillar data from the `pillar.example` file
  pillars_from_files:
    threatstack.sls: pillar.example
  pillars:
    top.sls:
      base:
        '*':
          - threatstack
    # Use this section (and comment out the `pillars_from_files` section)
    # to grab pillar data from environment variables
    # threatstack.sls:
    #   deploy_key: <%= ENV['TS_DEPLOY_KEY'] != nil ? ENV['TS_DEPLOY_KEY'] : 'ts_deploy_key' %>
    #   ts_agent_version: <%= ENV['TS_PACKAGE_VERSION'] %>
    #   <% if ENV['TS_CONFIG_ARGS'] %>
    #   ts_agent_config_args: <%= ENV['TS_CONFIG_ARGS'] %>
    #   <% end %>
    #   ts_agent_version: <%= ENV['TS_PACKAGE_VERSION'] %>
    # ts_configure_agent: <%= ENV['TS_CONFIGURE_AGENT'] %>
    # ts_agent_latest: <%= ENV['TS_AGENT_LATEST'] %>
    #   <% if ENV['TS_SETUP_ARGS'] %>
    #   ts_agent_extra_args: <%= ENV['TS_SETUP_ARGS'] %>
    #   <% end %>
  state_top:
    base:
      '*':
        - threatstack

platforms:
  - name: centos-7.6
  - name: debian-8.11
  - name: debian-9.6
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: ubuntu-18.04

suites:
  - name: default
