---
driver:
  name: docker

provisioner:
  name: salt_solo
  bootstrap_url: 'https://raw.githubusercontent.com/olhado/kitchen-salt/master/assets/install.sh'
  is_file_root: true
  pillars:
    top.sls:
      base:
        '*':
          - threatstack
    # Use this section (and comment out the `pillars_from_files` section)
    # to grab pillar data from environment variables
    threatstack.sls:
      deploy_key: <%= ENV['TS_DEPLOY_KEY'] != nil ? ENV['TS_DEPLOY_KEY'] : 'ts_deploy_key' %>
      <% if ENV['TS_PACKAGE_VERSION'] %>
      ts_agent_version: <%= ENV['TS_PACKAGE_VERSION'] %>
      <% end %>
      <% if ENV['TS_CONFIGURE_AGENT'] %>
      ts_configure_agent: <%= ENV['TS_CONFIGURE_AGENT'] %>
      <% end %>
      <% if ENV['TS_SETUP_ARGS'] %>
      ts_agent_extra_args: <%= ENV['TS_SETUP_ARGS'] %>
      <% end %>
      <% if ENV['TS_CONFIG_ARGS'] %>
      ts_agent_config_args: <%= ENV['TS_CONFIG_ARGS'] %>
      <% end %>
  # Use this section (and comment out the `threatstack.sls` definition in the `pillars` section)
  # to grab pillar data from the `pillar.example` file
  # pillars_from_files:
  #   threatstack.sls: pillar.example
  state_top:
    base:
      '*':
        - threatstack

platforms:
  - name: amazonlinux-1
    provisioner:
      salt_bootstrap_options: '-R archive.repo.saltstack.com stable 2019.2'
      pillars:
        threatstack.sls:
          pkg_url: https://pkg.threatstack.com/v2/Amazon/1
          gpg_key: https://app.threatstack.com/RPM-GPG-KEY-THREATSTACK
          gpg_key_file: '/etc/pki/rpm-gpg/RPM-GPG-KEY-THREATSTACK'
          gpg_key_file_uri: 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-THREATSTACK'
    driver_config:
      image: amazonlinux:1
      run_command: /sbin/init
      privileged: true
      run_options:
        env: container=docker
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup
      provision_command:
        - yum install -y ruby24
        - alternatives --set ruby /usr/bin/ruby2.4
        - yum install -y audit initscripts
        - sed -i 's/local_events = yes/local_events = no/g' /etc/audit/auditd.conf
        - chkconfig auditd on
  - name: amazonlinux-2
    provisioner:
      pillars:
        threatstack.sls:
          pkg_url: https://pkg.threatstack.com/v2/Amazon/2
          gpg_key: https://app.threatstack.com/RPM-GPG-KEY-THREATSTACK
          gpg_key_file: '/etc/pki/rpm-gpg/RPM-GPG-KEY-THREATSTACK'
          gpg_key_file_uri: 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-THREATSTACK'
    driver_config:
      image: amazonlinux:2
      run_command: /sbin/init
      privileged: true
      run_options:
        env: container=docker
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup
      provision_command:
        - amazon-linux-extras install ruby2.6
        - yum install -y ruby-devel gcc make
        - gem install io-console --install-dir=/tmp/verifier/gems
        - chown -R kitchen:kitchen /tmp/verifier
        - yum install -y audit initscripts
        - sed -i 's/local_events = yes/local_events = no/g' /etc/audit/auditd.conf
        - systemctl enable auditd.service
  - name: centos-7
    provisioner:
      salt_bootstrap_options: '-R archive.repo.saltstack.com stable 2019.2'
      pillars:
        threatstack.sls:
          pkg_url: https://pkg.threatstack.com/v2/EL/7
          gpg_key: https://app.threatstack.com/RPM-GPG-KEY-THREATSTACK
          gpg_key_file: '/etc/pki/rpm-gpg/RPM-GPG-KEY-THREATSTACK'
          gpg_key_file_uri: 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-THREATSTACK'
    driver_config:
      image: centos:7
      run_command: /sbin/init
      privileged: true
      run_options:
        env: container=docker
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup
      provision_command:
        - yum install -y ruby ruby-devel git
        - yum install -y centos-release-scl-rh
        - yum install -y rh-ruby26
        - mkdir -p /opt/chef/embedded/bin
        - ln -s "/opt/rh/rh-ruby26/root/usr/bin/gem" /opt/chef/embedded/bin/
        - ln -s "/opt/rh/rh-ruby26/root/usr/bin/ruby" /opt/chef/embedded/bin/
        - |
          printf "LD_LIBRARY_PATH=/opt/rh/rh-ruby26/root/usr/local/lib64:/opt/rh/rh-ruby26/root/usr/lib64\n"\
          >> /etc/environment
        - yum install -y audit initscripts
        - sed -i 's/local_events = yes/local_events = no/g' /etc/audit/auditd.conf
        - systemctl enable auditd.service
  - name: centos-8
    provisioner:
      pillars:
        threatstack.sls:
          pkg_url: https://pkg.threatstack.com/v2/EL/8
          gpg_key: https://app.threatstack.com/RPM-GPG-KEY-THREATSTACK
          gpg_key_file: '/etc/pki/rpm-gpg/RPM-GPG-KEY-THREATSTACK'
          gpg_key_file_uri: 'file:///etc/pki/rpm-gpg/RPM-GPG-KEY-THREATSTACK'
    driver_config:
      image: centos:8
      run_command: /sbin/init
      privileged: true
      run_options:
        env: container=docker
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup
      provision_command:
        - yum install -y audit initscripts
        - sed -i 's/local_events = yes/local_events = no/g' /etc/audit/auditd.conf
        - systemctl enable auditd.service
  - name: debian-8
    provisioner:
      salt_bootstrap_options: '-R archive.repo.saltstack.com'
      pillars:
        threatstack.sls:
          pkg_url: https://pkg.threatstack.com/v2/Ubuntu
          gpg_key: https://app.threatstack.com/APT-GPG-KEY-THREATSTACK
          pkg_component: main
    driver_config:
      image: debian:8
      run_command: /sbin/init
      cap_add:
        - SYS_ADMIN
      run_options:
        env: container=docker
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup
      provision_command:
        - |
          apt-get install -y checkinstall build-essential zlib1g-dev libssl-dev libreadline6-dev libyaml-dev wget && \
          wget https://cache.ruby-lang.org/pub/ruby/2.6/ruby-2.6.6.tar.gz && \
          tar xfz ruby-2.6.6.tar.gz && \
          echo "364b143def360bac1b74eb56ed60b1a0dca6439b00157ae11ff77d5cd2e92291 ruby-2.6.6.tar.gz" | sha256sum -c && \
          cd ruby-2.6.6 && ./configure && make && make install && rm ../ruby-2.6.6.tar.gz
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable ssh.service
  - name: debian-9
    provisioner:
      pillars:
        threatstack.sls:
          pkg_url: https://pkg.threatstack.com/v2/Ubuntu
          gpg_key: https://app.threatstack.com/APT-GPG-KEY-THREATSTACK
          pkg_component: main
    driver_config:
      image: debian:9
      run_command: /bin/systemd
      cap_add:
        - SYS_ADMIN
      run_options:
        env: container=docker
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable ssh.service
  - name: debian-10
    provisioner:
      pillars:
        threatstack.sls:
          pkg_url: https://pkg.threatstack.com/v2/Ubuntu
          gpg_key: https://app.threatstack.com/APT-GPG-KEY-THREATSTACK
          pkg_component: main
    driver_config:
      image: debian:10
      run_command: /sbin/init
      cap_add:
        - SYS_ADMIN
      run_options:
        env: container=docker
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable ssh.service
  - name: ubuntu-16.04
    provisioner:
      pillars:
        threatstack.sls:
          pkg_url: https://pkg.threatstack.com/v2/Ubuntu
          gpg_key: https://app.threatstack.com/APT-GPG-KEY-THREATSTACK
          pkg_component: main
    driver_config:
      image: ubuntu:16.04
      run_command: /sbin/init
      cap_add:
        - SYS_ADMIN
      run_options:
        env: container=docker
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable ssh.service
  - name: ubuntu-18.04
    provisioner:
      pillars:
        threatstack.sls:
          pkg_url: https://pkg.threatstack.com/v2/Ubuntu
          gpg_key: https://app.threatstack.com/APT-GPG-KEY-THREATSTACK
          pkg_component: main
    driver_config:
      image: ubuntu:18.04
      run_command: /sbin/init
      cap_add:
        - SYS_ADMIN
      run_options:
        env: container=docker
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable ssh.service
  - name: ubuntu-20.04
    provisioner:
      pillars:
        threatstack.sls:
          pkg_url: https://pkg.threatstack.com/v2/Ubuntu
          gpg_key: https://app.threatstack.com/APT-GPG-KEY-THREATSTACK
          pkg_component: main
    driver_config:
      image: ubuntu:20.04
      run_command: /sbin/init
      cap_add:
        - SYS_ADMIN
      run_options:
        env: container=docker
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable ssh.service

suites:
  - name: default
  - name: custom
    provisioner:
      pillars:
        threatstack.sls:
          ts_agent_config_args: "--set log.maxSize 22"
